
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MyApp from "./page";
import { auth } from "@/auth"
import { SessionProvider } from "next-auth/react";
import NavBar from "@/components/NavBar";
import { Toaster } from "react-hot-toast";
import AuthWrapper from "./AuthWraper";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  const session = await auth()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthWrapper session={session}>
       {children}

       </AuthWrapper>
      </body>
    </html>
  );
}
