import { Jugadores } from "@/infraestrcuture/entities/jugadores";

export const jugadores: Jugadores[] = [
  {
    nombre: "Carlos",
    apellido: "Gomez",
    edad: 28,
    estatura: 1.8,
    foto: "/avatares/avatar1.jpg",
    equipo: "/imagenes/logo1.jpg",
  },
  {
    nombre: "Luis",
    apellido: "Martínez",
    edad: 25,
    estatura: 1.75,
    foto: "/avatares/avatar2.jpg",
    equipo: "/imagenes/logo2.jpg",
  },
  {
    nombre: "Juan",
    apellido: "López",
    edad: 30,
    estatura: 1.85,
    foto: "/avatares/avatar3.jpg",
    equipo: "/imagenes/logo3.jpg",
  },
  {
    nombre: "Miguel",
    apellido: "Fernández",
    edad: 27,
    estatura: 1.78,
    foto: "/avatares/avatar4.jpg",
    equipo: "/imagenes/logo4.jpg",
  },
  {
    nombre: "Andrés",
    apellido: "Hernández",
    edad: 26,
    estatura: 1.82,
    foto: "/avatares/avatar5.jpg",
    equipo: "/imagenes/logo5.jpg",
  },
  {
    nombre: "Santiago",
    apellido: "García",
    edad: 24,
    estatura: 1.77,
    foto: "/avatares/avatar6.jpg",
    equipo: "/imagenes/logo6.jpg",
  },
  {
    nombre: "Pedro",
    apellido: "Rodríguez",
    edad: 29,
    estatura: 1.79,
    foto: "/avatares/avatar7.jpg",
    equipo: "/imagenes/logo7.jpg",
  },
  {
    nombre: "Daniel",
    apellido: "Pérez",
    edad: 32,
    estatura: 1.83,
    foto: "/avatares/avatar8.jpg",
    equipo: "/imagenes/logo8.jpg",
  },
  {
    nombre: "Francisco",
    apellido: "Sánchez",
    edad: 31,
    estatura: 1.81,
    foto: "/avatares/avatar9.jpg",
    equipo: "/imagenes/logo9.jpg",
  },
  {
    nombre: "Javier",
    apellido: "Ramírez",
    edad: 23,
    estatura: 1.74,
    foto: "/avatares/avatar10.jpg",
    equipo: "/imagenes/logo10.jpg",
  },
  {
    nombre: "Eduardo",
    apellido: "Torres",
    edad: 28,
    estatura: 1.8,
    foto: "/avatares/avatar11.jpg",
    equipo: "/imagenes/logo11.jpg",
  },
  {
    nombre: "Roberto",
    apellido: "Álvarez",
    edad: 25,
    estatura: 1.76,
    foto: "/avatares/avatar12.jpg",
    equipo: "/imagenes/logo12.jpg",
  },
  {
    nombre: "Antonio",
    apellido: "Ruiz",
    edad: 33,
    estatura: 1.88,
    foto: "/avatares/avatar13.jpg",
    equipo: "/imagenes/logo13.jpg",
  },
  {
    nombre: "Rafael",
    apellido: "González",
    edad: 27,
    estatura: 1.78,
    foto: "/avatares/avatar14.jpg",
    equipo: "/imagenes/logo14.jpg",
  },
  {
    nombre: "David",
    apellido: "Morales",
    edad: 26,
    estatura: 1.8,
    foto: "/avatares/avatar15.jpg",
    equipo: "/imagenes/logo15.jpg",
  },
  {
    nombre: "Marco",
    apellido: "Vázquez",
    edad: 29,
    estatura: 1.82,
    foto: "/avatares/avatar16.jpg",
    equipo: "/imagenes/logo16.jpg",
  },
  {
    nombre: "Felipe",
    apellido: "Castro",
    edad: 24,
    estatura: 1.73,
    foto: "/avatares/avatar17.jpg",
    equipo: "/imagenes/logo7.jpg",
  },
  {
    nombre: "Oscar",
    apellido: "Jiménez",
    edad: 28,
    estatura: 1.79,
    foto: "/avatares/avatar18.jpg",
    equipo: "/imagenes/logo8.jpg",
  },
];
